### ISSUE TITLE
Calling Seek rapidly causes out of range crash

### ISSUE THREAD

**Issue by MarkKremer** [gopxl/beep#125]
Calling this function repeatedly causes a crash

```golang
// seek from the current position by step seconds
func seek(step int) {
	seekTo := currentTrack.stream.Position() + step*sr.N(time.Second)
	if seekTo < 0 {
		seekTo = 0
	} else if seekTo > currentTrack.stream.Len() {
		nextTrack()
	}

	currentTrack.stream.Seek(seekTo)
}
```

I'm pretty sure this had something to do with seeking to a part of the stream before it's buffered, but I'm not sure how to avoid it. I'm guessing there's a check for it or something, but I can't find it.
Thanks in advance.

Error message:
```
panic: runtime error: slice bounds out of range [5860:4608] [recovered]
        panic: runtime error: slice bounds out of range [5860:4608]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
        /usr/local/bin/go/pkg/mod/github.com/rivo/tview@v0.0.0-20231007183732-6c844bdc5f7a/application.go:251 +0x4d
panic({0xa56860, 0xc00002a168})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/hajimehoshi/go-mp3.(*Decoder).Seek(0xc00009e660, 0x0?, 0x1?)
        /usr/local/bin/go/pkg/mod/github.com/hajimehoshi/go-mp3@v0.3.4/decode.go:111 +0x30d
github.com/faiface/beep/mp3.(*decoder).Seek(0xc00007c140, 0x1df9b9)
        /usr/local/bin/go/pkg/mod/github.com/faiface/beep@v1.1.0/mp3/decode.go:90 +0x105
main.seek(0x5)
        /home/vojislav/Documents/music-player-go/audioplayback.go:171 +0xaf
main.trackInputHandler(0x0?)
        /home/vojislav/Documents/music-player-go/tview.go:133 +0x1e5
main.appInputHandler(0xc0000e4020)
        /home/vojislav/Documents/music-player-go/tview.go:445 +0x167
github.com/rivo/tview.(*Application).Run(0xc000290000)
        /usr/local/bin/go/pkg/mod/github.com/rivo/tview@v0.0.0-20231007183732-6c844bdc5f7a/application.go:327 +0x42b
main.main()
        /home/vojislav/Documents/music-player-go/main.go:84 +0x20a
exit status 2
```

Original issue: https://github.com/faiface/beep/issues/168

**Comment by MarkKremer** [comment]
Probably solved in the original issue. Closing
