### ISSUE TITLE
index out of range panic

### ISSUE THREAD

**Issue by uzudil** [gopxl/beep#197]
First, thanks for maintaining this great library! I use it for my game [enalim](https://uzudil.itch.io/enalim).

I intermittently see the following error:

panic: runtime error: index out of range [-1]

goroutine 9339 [running]:
github.com/gopxl/beep/v2.(*Mixer).Stream(0xc000eb26a0, {0xc07bf9c000, 0x200, 0x200})
	/Users/gtorok/go/pkg/mod/github.com/gopxl/beep/v2@v2.1.0/mixer.go:66 +0x371
github.com/gopxl/beep/v2.(*Mixer).Stream(0xc000eb2680, {0xc07bf86000, 0x200, 0x200})
	/Users/gtorok/go/pkg/mod/github.com/gopxl/beep/v2@v2.1.0/mixer.go:54 +0x1bd
github.com/gopxl/beep/v2/effects.(*Volume).Stream(0xc032a79770, {0xc07bf86000, 0x200, 0x200})
	/Users/gtorok/go/pkg/mod/github.com/gopxl/beep/v2@v2.1.0/effects/volume.go:31 +0x36
github.com/gopxl/beep/v2.(*Mixer).Stream(0x10a6e3620, {0xc03aa86000, 0x89d, 0x89d})
	/Users/gtorok/go/pkg/mod/github.com/gopxl/beep/v2@v2.1.0/mixer.go:54 +0x1bd
github.com/gopxl/beep/v2/speaker.(*sampleReader).stream(0xc000052008?, {0xc03aa86000?, 0x10955d9a5?, 0xc0a75a4180?})
	/Users/gtorok/go/pkg/mod/github.com/gopxl/beep/v2@v2.1.0/speaker/speaker.go:207 +0xba
github.com/gopxl/beep/v2/speaker.(*sampleReader).Read(0xc032a79da0, {0xc037aa5900, 0x2274, 0xc000134d28?})
	/Users/gtorok/go/pkg/mod/github.com/gopxl/beep/v2@v2.1.0/speaker/speaker.go:176 +0xc5
github.com/ebitengine/oto/v3/internal/mux.(*playerImpl).read(0xc06feb5e58?, {0xc037aa5900?, 0x109a77ea0?, 0x109e6d6e0?})
	/Users/gtorok/go/pkg/mod/github.com/ebitengine/oto/v3@v3.2.0/internal/mux/mux.go:268 +0xc2
github.com/ebitengine/oto/v3/internal/mux.(*playerImpl).readSourceToBuffer(0xc000361710)
	/Users/gtorok/go/pkg/mod/github.com/ebitengine/oto/v3@v3.2.0/internal/mux/mux.go:529 +0x13a
github.com/ebitengine/oto/v3/internal/mux.(*Mux).loop(0xc000ed55c0)
	/Users/gtorok/go/pkg/mod/github.com/ebitengine/oto/v3@v3.2.0/internal/mux/mux.go:108 +0x1f1
created by github.com/ebitengine/oto/v3/internal/mux.New in goroutine 1
	/Users/gtorok/go/pkg/mod/github.com/ebitengine/oto/v3@v3.2.0/internal/mux/mux.go:69 +0xf8

Thanks!

**Comment by MarkKremer** [comment]
Love to see Beep being used! Your game looks cool!

From only the stack trace I can only make some guesses to what's happening:
1. Some concurrency error. Make sure that when you make changes to the `Mixer` (`Add` or `Clear`) that you [`Lock`](https://pkg.go.dev/github.com/gopxl/beep/v2@v2.1.0/speaker#Lock) the speaker. See [the tutorial](https://github.com/gopxl/beep/wiki/Composing-and-controlling).
2. I see that one Mixer is used by another. Make sure the Mixer isn't consuming itself.

If that doesn't help, I would appreciate if you could share some code so we can further debug the problem.

**Comment by MarkKremer** [comment]
I've made a PR to check whether the mixer has been cleared during streaming to prevent the panic.

Both faiface's implementation and ours remove streamers which are done playing but our version is a bit more aggressive about it and removes them when they return less than the requested samples instead of waiting for the `!ok` signal that has to follow it. So it's possible that you don't need the clear for your use case.

**Comment by MarkKremer** [comment]
I think we tackled the problem so it's just out of curiosity. If it isn't a hassle, please share :)

Also, blind debugging is more difficult than with a small reproduction snippet.
